services:
  - xvfb

before_install:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start

language: r

warnings_are_errors: true

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
